server:
  port: 8080
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    open-in-view: false
      # Achtung bei Tests, ggf. eigenes "test"-Profil verwenden
      # hibernate:
    # ddl-auto: validate
application:
  customers:
    initialization:
      enabled: ${CUSTOMERS_INITIALIZATION_ENABLED:false}